<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Mawadi3Print</AssemblyName>
    <RootNamespace>Mawadi3Print</RootNamespace>
    <Version>1.0.0</Version>
    <SatelliteResourceLanguages>ar;fr</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="QuestPDF" Version="2024.12.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\logo.png" />
  </ItemGroup>

</Project>